In [1]:
#import statements
import pandas as pd

In [2]:
Condo_df = pd.read_csv("Condo_cleanedDF.csv")

In [3]:
Condo_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,MEDIAN SALE PRICE YOY (%),HOMES SOLD,HOMES SOLD YOY (%),Year,Month,Month Name,Quarter,Season,Year-Month,Period Length (Days)
0,Monthly,2026-06-01,2026-06-30,Alabama,Condo/Co-op,Homeowner,3.5,104048.0,8.82,36.23,...,11.90,271.0,2.08,2026,6,June,2,Summer,2026-06,29
1,Monthly,2026-05-01,2026-05-31,Alabama,Condo/Co-op,Homeowner,3.5,104751.0,19.42,36.47,...,23.32,308.0,21.26,2026,5,May,2,Spring,2026-05,30
2,Monthly,2026-04-01,2026-04-30,Alabama,Condo/Co-op,Homeowner,3.5,102006.0,11.84,35.52,...,15.71,292.0,27.51,2026,4,April,2,Spring,2026-04,29
3,Monthly,2026-03-01,2026-03-31,Alabama,Condo/Co-op,Homeowner,3.5,92864.0,-6.85,32.33,...,-3.03,265.0,18.83,2026,3,March,1,Spring,2026-03,30
4,Monthly,2026-02-01,2026-02-28,Alabama,Condo/Co-op,Homeowner,3.5,90391.0,6.14,31.47,...,13.53,187.0,14.02,2026,2,February,1,Winter,2026-02,27

In [4]:
StarterHome_df = pd.read_csv("StarterHome_cleanedDF.csv")

In [5]:
StarterHome_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,MEDIAN SALE PRICE YOY (%),HOMES SOLD,HOMES SOLD YOY (%),Year,Month,Month Name,Quarter,Season,Year-Month,Period Length (Days)
0,Monthly,2026-06-01,2026-06-30,Alabama,Starter Home,Homeowner,3.5,57721.0,2.52,20.10,...,5.42,4851.0,2.54,2026,6,June,2,Summer,2026-06,29
1,Monthly,2026-05-01,2026-05-31,Alabama,Starter Home,Homeowner,3.5,57273.0,1.18,19.94,...,4.49,4755.0,2.52,2026,5,May,2,Spring,2026-05,30
2,Monthly,2026-04-01,2026-04-30,Alabama,Starter Home,Homeowner,3.5,56255.0,-0.29,19.59,...,3.16,4312.0,4.91,2026,4,April,2,Spring,2026-04,29
3,Monthly,2026-03-01,2026-03-31,Alabama,Starter Home,Homeowner,3.5,55239.0,0.32,19.23,...,4.43,3918.0,6.84,2026,3,March,1,Spring,2026-03,30
4,Monthly,2026-02-01,2026-02-28,Alabama,Starter Home,Homeowner,3.5,54067.0,-2.53,18.82,...,4.26,3886.0,6.61,2026,2,February,1,Winter,2026-02,27

In [6]:
SingleFamily_df = pd.read_csv("SingleFamily_cleanedDF.csv")

In [7]:
SingleFamily_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,DOWN PAYMENT AMOUNT ($) Prop,INCOME REQUIRED YOY (%) Prop,SHARE OF INCOME ON HOUSING (%) Prop,SHARE OF INCOME ON HOUSING YOY (PPTS) Prop,AFFORDABLE LISTING SHARE (%) Prop,AFFORDABLE LISTING SHARE YOY (PPTS) Prop,YEARS TO SAVE DOWN PAYMENT YOY (%) Prop,MEDIAN SALE PRICE YOY (%) Prop,HOMES SOLD YOY (%) Prop,Season
0,Monthly,2026-06-01,2026-06-30,Alabama,Single Family,Homeowner,3.5,90532.0,-1.49,31.52,...,106.33,-0.0149,0.3152,-0.0181,0.4057,0.0287,-0.0276,0.0130,0.0832,Summer
1,Monthly,2026-05-01,2026-05-31,Alabama,Single Family,Homeowner,3.5,90652.0,-0.56,31.56,...,106.92,-0.0056,0.3156,-0.0150,0.4212,0.0419,-0.0142,0.0269,0.0091,Spring
2,Monthly,2026-04-01,2026-04-30,Alabama,Single Family,Homeowner,3.5,88160.0,0.65,30.69,...,104.97,0.0065,0.3069,-0.0107,0.4302,0.0365,-0.0003,0.0413,0.0217,Spring
3,Monthly,2026-03-01,2026-03-31,Alabama,Single Family,Homeowner,3.5,86472.0,-1.26,30.11,...,104.29,-0.0126,0.3011,-0.0165,0.4482,0.0405,-0.0133,0.0279,0.0641,Spring
4,Monthly,2026-02-01,2026-02-28,Alabama,Single Family,Homeowner,3.5,82901.0,-3.96,28.86,...,101.12,-0.0396,0.2886,-0.0244,0.4824,0.0765,-0.0137,0.0274,0.0637,Winter

In [8]:
Townhouse_df = pd.read_csv("Townhouse_cleanedDF.csv")

In [9]:
Townhouse_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,DOWN PAYMENT AMOUNT ($) Prop,INCOME REQUIRED YOY (%) Prop,SHARE OF INCOME ON HOUSING (%) Prop,SHARE OF INCOME ON HOUSING YOY (PPTS) Prop,AFFORDABLE LISTING SHARE (%) Prop,AFFORDABLE LISTING SHARE YOY (PPTS) Prop,YEARS TO SAVE DOWN PAYMENT YOY (%) Prop,MEDIAN SALE PRICE YOY (%) Prop,HOMES SOLD YOY (%) Prop,Season
0,Monthly,2026-06-01,2026-06-30,Alabama,Townhouse,Homeowner,3.5,83234.0,5.18,28.98,...,97.75,0.0518,0.2898,0.0028,0.5095,-0.0076,0.0383,0.0816,0.1715,Summer
1,Monthly,2026-05-01,2026-05-31,Alabama,Townhouse,Homeowner,3.5,77895.0,-2.20,27.12,...,91.88,-0.0220,0.2712,-0.0176,0.5041,-0.0220,-0.0304,0.0100,-0.1429,Spring
2,Monthly,2026-04-01,2026-04-30,Alabama,Townhouse,Homeowner,3.5,73462.0,-11.84,25.58,...,87.47,-0.1184,0.2558,-0.0464,0.5293,0.0157,-0.1244,-0.0879,-0.1386,Spring
3,Monthly,2026-03-01,2026-03-31,Alabama,Townhouse,Homeowner,3.5,74524.0,4.98,25.95,...,89.88,0.0498,0.2595,0.0020,0.5407,0.0220,0.0491,0.0928,-0.0126,Spring
4,Monthly,2026-02-01,2026-02-28,Alabama,Townhouse,Homeowner,3.5,73030.0,-7.96,25.43,...,89.08,-0.0796,0.2543,-0.0335,0.5936,0.1027,-0.0549,-0.0155,-0.1515,Winter

In [10]:
singleFam_columns = set(SingleFamily_df.columns) #Tara's Cleaned Dataset Columns
townhouse_columns = set(Townhouse_df.columns)    #Tara's Cleaned Dataset Columns

In [11]:
condo_columns = set(Condo_df.columns) #Justin's Cleaned Dataset Columns
StarterHome_columns = set(StarterHome_df.columns)    #Justin's Cleaned Dataset Columns

In [12]:
#in Tara's Dataset, not in Justin dataset
print("Columns in Single Family, NOT in Condo: ")
print(singleFam_columns - condo_columns)

Columns in Single Family, NOT in Condo:
{'AFFORDABLE LISTING SHARE (%) Prop', 'SHARE OF INCOME ON HOUSING (%) Prop', 'AFFORDABLE LISTING SHARE YOY (PPTS) Prop', 'HOMES SOLD YOY (%) Prop', 'YEARS TO SAVE DOWN PAYMENT YOY (%) Prop', 'MEDIAN SALE PRICE YOY (%) Prop', 'SHARE OF INCOME ON HOUSING YOY (PPTS) Prop', 'INCOME REQUIRED YOY (%) Prop', 'Month_Name', 'DOWN PAYMENT AMOUNT ($) Prop'}

In [13]:
#in Tara's Dataset, not in Justin dataset
print("Columns in Single Family, NOT in Starter Home: ")
print(singleFam_columns - StarterHome_columns)

Columns in Single Family, NOT in Starter Home:
{'AFFORDABLE LISTING SHARE (%) Prop', 'SHARE OF INCOME ON HOUSING (%) Prop', 'AFFORDABLE LISTING SHARE YOY (PPTS) Prop', 'HOMES SOLD YOY (%) Prop', 'YEARS TO SAVE DOWN PAYMENT YOY (%) Prop', 'MEDIAN SALE PRICE YOY (%) Prop', 'SHARE OF INCOME ON HOUSING YOY (PPTS) Prop', 'INCOME REQUIRED YOY (%) Prop', 'Month_Name', 'DOWN PAYMENT AMOUNT ($) Prop'}

In [14]:
#in Justin's Dataset, not in Tara dataset
print("Columns in Condo, NOT in Single Family: ")
print(condo_columns - singleFam_columns)

Columns in Condo, NOT in Single Family:
{'Month Name', 'Year-Month', 'Period Length (Days)'}

In [15]:
#in Justin's Dataset, not in Tara dataset
print("Columns in Starter Home, NOT in Single Family: ")
print(StarterHome_columns - singleFam_columns)

Columns in Starter Home, NOT in Single Family:
{'Month Name', 'Year-Month', 'Period Length (Days)'}

In [16]:
#in Tara's Dataset, not in Justin dataset
print("Columns in Townhouse, NOT in Condo: ")
print(townhouse_columns - condo_columns)

Columns in Townhouse, NOT in Condo:
{'AFFORDABLE LISTING SHARE (%) Prop', 'SHARE OF INCOME ON HOUSING (%) Prop', 'AFFORDABLE LISTING SHARE YOY (PPTS) Prop', 'HOMES SOLD YOY (%) Prop', 'YEARS TO SAVE DOWN PAYMENT YOY (%) Prop', 'MEDIAN SALE PRICE YOY (%) Prop', 'SHARE OF INCOME ON HOUSING YOY (PPTS) Prop', 'INCOME REQUIRED YOY (%) Prop', 'Month_Name', 'DOWN PAYMENT AMOUNT ($) Prop'}

In [17]:
#in Tara's Dataset, not in Justin dataset
print("Columns in Townhouse, NOT in Starter Home: ")
print(townhouse_columns - StarterHome_columns)

Columns in Townhouse, NOT in Starter Home:
{'AFFORDABLE LISTING SHARE (%) Prop', 'SHARE OF INCOME ON HOUSING (%) Prop', 'AFFORDABLE LISTING SHARE YOY (PPTS) Prop', 'HOMES SOLD YOY (%) Prop', 'YEARS TO SAVE DOWN PAYMENT YOY (%) Prop', 'MEDIAN SALE PRICE YOY (%) Prop', 'SHARE OF INCOME ON HOUSING YOY (PPTS) Prop', 'INCOME REQUIRED YOY (%) Prop', 'Month_Name', 'DOWN PAYMENT AMOUNT ($) Prop'}

In [18]:
#in Justin's Dataset, not in Tara dataset
print("Columns in Condo, NOT in Townhouse: ")
print(condo_columns - townhouse_columns)

Columns in Condo, NOT in Townhouse:
{'Month Name', 'Year-Month', 'Period Length (Days)'}

In [19]:
#in Justins's Dataset, not in Tara dataset
print("Columns in Starter Home, NOT in Townhouse: ")
print(StarterHome_columns - townhouse_columns)

Columns in Starter Home, NOT in Townhouse:
{'Month Name', 'Year-Month', 'Period Length (Days)'}

**Alterations Needed for Every Dataset**

* Justin: Condo and Starter Home

    * Add prop columns in


* Tara: Single Family and Townhouse

    * change Month_Name to Month Name (rename column)
    * Add Year-Month col
    * Add Period Length (Days)

In [20]:
#the percent columns missing for justins dataset
percent_cols = [
    'DOWN PAYMENT AMOUNT ($)',
    'INCOME REQUIRED YOY (%)',
    'SHARE OF INCOME ON HOUSING (%)',
    'SHARE OF INCOME ON HOUSING YOY (PPTS)',
    'AFFORDABLE LISTING SHARE (%)',
    'AFFORDABLE LISTING SHARE YOY (PPTS)',
    'YEARS TO SAVE DOWN PAYMENT YOY (%)',
    'MEDIAN SALE PRICE YOY (%)',
    'HOMES SOLD YOY (%)'
]

In [21]:
#double checking that the data types of percent_cols are currently float values:
for col in percent_cols:
    print("col name: ", col, " data type: ", Condo_df[col].dtype)

col name:  DOWN PAYMENT AMOUNT ($)  data type:  float64
col name:  INCOME REQUIRED YOY (%)  data type:  float64
col name:  SHARE OF INCOME ON HOUSING (%)  data type:  float64
col name:  SHARE OF INCOME ON HOUSING YOY (PPTS)  data type:  float64
col name:  AFFORDABLE LISTING SHARE (%)  data type:  float64
col name:  AFFORDABLE LISTING SHARE YOY (PPTS)  data type:  float64
col name:  YEARS TO SAVE DOWN PAYMENT YOY (%)  data type:  float64
col name:  MEDIAN SALE PRICE YOY (%)  data type:  float64
col name:  HOMES SOLD YOY (%)  data type:  float64

In [22]:
#double checking that the data types of percent_cols are currently float values:
for col in percent_cols:
    print("col name: ", col, " data type: ", StarterHome_df[col].dtype)

col name:  DOWN PAYMENT AMOUNT ($)  data type:  float64
col name:  INCOME REQUIRED YOY (%)  data type:  float64
col name:  SHARE OF INCOME ON HOUSING (%)  data type:  float64
col name:  SHARE OF INCOME ON HOUSING YOY (PPTS)  data type:  float64
col name:  AFFORDABLE LISTING SHARE (%)  data type:  float64
col name:  AFFORDABLE LISTING SHARE YOY (PPTS)  data type:  float64
col name:  YEARS TO SAVE DOWN PAYMENT YOY (%)  data type:  float64
col name:  MEDIAN SALE PRICE YOY (%)  data type:  float64
col name:  HOMES SOLD YOY (%)  data type:  float64

In [23]:
#Condo: proportionalizing the percent columns, giving them a new column (a copy of the original percentage col / 100)
for col in percent_cols:
    newColName = col + ' Prop'
    Condo_df[newColName] = Condo_df[col] / 100

In [24]:
#Starter Home: proportionalizing the percent columns, giving them a new column (a copy of the original percentage col / 100)
for col in percent_cols:
    newColName = col + ' Prop'
    StarterHome_df[newColName] = StarterHome_df[col] / 100

In [25]:
Condo_df.columns

Index(['FREQUENCY', 'PERIOD BEGIN', 'PERIOD END', 'REGION NAME',
       'PROPERTY TYPE', 'INCOME GROUP', 'DOWN PAYMENT PERCENT (%)',
       'INCOME REQUIRED ($)', 'INCOME REQUIRED YOY (%)',
       'SHARE OF INCOME ON HOUSING (%)',
       'SHARE OF INCOME ON HOUSING YOY (PPTS)', 'AFFORDABLE LISTING SHARE (%)',
       'AFFORDABLE LISTING SHARE YOY (PPTS)', 'YEARS TO SAVE DOWN PAYMENT',
       'YEARS TO SAVE DOWN PAYMENT YOY (%)', 'MONTHLY HOUSING PAYMENT ($)',
       'MONTHLY MORTGAGE PAYMENT ($)', 'MONTHLY PROPERTY TAX ($)',
       'MONTHLY PROPERTY INSURANCE ($)', 'MONTHLY PMI ($)',
       'DOWN PAYMENT AMOUNT ($)', 'MEDIAN HOUSEHOLD INCOME ($)',
       'MEDIAN SALE PRICE ($)', 'MEDIAN SALE PRICE YOY (%)', 'HOMES SOLD',
       'HOMES SOLD YOY (%)', 'Year', 'Month', 'Month Name', 'Quarter',
       'Season', 'Year-Month', 'Period Length (Days)',
       'DOWN PAYMENT AMOUNT ($) Prop', 'INCOME REQUIRED YOY (%) Prop',
       'SHARE OF INCOME ON HOUSING (%) Prop',
       'SHARE OF INCOME ON HOUSING YOY (PPTS) Prop',
       'AFFORDABLE LISTING SHARE (%) Prop',
       'AFFORDABLE LISTING SHARE YOY (PPTS) Prop',
       'YEARS TO SAVE DOWN PAYMENT YOY (%) Prop',
       'MEDIAN SALE PRICE YOY (%) Prop', 'HOMES SOLD YOY (%) Prop'],
      dtype='object')

In [26]:
StarterHome_df.columns

Index(['FREQUENCY', 'PERIOD BEGIN', 'PERIOD END', 'REGION NAME',
       'PROPERTY TYPE', 'INCOME GROUP', 'DOWN PAYMENT PERCENT (%)',
       'INCOME REQUIRED ($)', 'INCOME REQUIRED YOY (%)',
       'SHARE OF INCOME ON HOUSING (%)',
       'SHARE OF INCOME ON HOUSING YOY (PPTS)', 'AFFORDABLE LISTING SHARE (%)',
       'AFFORDABLE LISTING SHARE YOY (PPTS)', 'YEARS TO SAVE DOWN PAYMENT',
       'YEARS TO SAVE DOWN PAYMENT YOY (%)', 'MONTHLY HOUSING PAYMENT ($)',
       'MONTHLY MORTGAGE PAYMENT ($)', 'MONTHLY PROPERTY TAX ($)',
       'MONTHLY PROPERTY INSURANCE ($)', 'MONTHLY PMI ($)',
       'DOWN PAYMENT AMOUNT ($)', 'MEDIAN HOUSEHOLD INCOME ($)',
       'MEDIAN SALE PRICE ($)', 'MEDIAN SALE PRICE YOY (%)', 'HOMES SOLD',
       'HOMES SOLD YOY (%)', 'Year', 'Month', 'Month Name', 'Quarter',
       'Season', 'Year-Month', 'Period Length (Days)',
       'DOWN PAYMENT AMOUNT ($) Prop', 'INCOME REQUIRED YOY (%) Prop',
       'SHARE OF INCOME ON HOUSING (%) Prop',
       'SHARE OF INCOME ON HOUSING YOY (PPTS) Prop',
       'AFFORDABLE LISTING SHARE (%) Prop',
       'AFFORDABLE LISTING SHARE YOY (PPTS) Prop',
       'YEARS TO SAVE DOWN PAYMENT YOY (%) Prop',
       'MEDIAN SALE PRICE YOY (%) Prop', 'HOMES SOLD YOY (%) Prop'],
      dtype='object')

In [27]:
#Tara's Datasets: rename 'Month_Name' to 'Month Name' to align with Justin's Datasets

SingleFamily_df = SingleFamily_df.rename(columns={'Month_Name': 'Month Name'})
Townhouse_df = Townhouse_df.rename(columns={'Month_Name': 'Month Name'})

In [28]:
print(Condo_df['Year-Month'].dtype)

object

In [29]:
print(StarterHome_df['Year-Month'].dtype)

object

In [31]:
SingleFamily_df['PERIOD BEGIN'] = pd.to_datetime(SingleFamily_df['PERIOD BEGIN'])
Townhouse_df['PERIOD BEGIN'] = pd.to_datetime(Townhouse_df['PERIOD BEGIN'])

In [32]:
SingleFamily_df['Year-Month'] = SingleFamily_df['PERIOD BEGIN'].dt.strftime('%Y-%m')
Townhouse_df['Year-Month'] = Townhouse_df['PERIOD BEGIN'].dt.strftime('%Y-%m')

In [34]:
SingleFamily_df['PERIOD END'] = pd.to_datetime(SingleFamily_df['PERIOD END'])
Townhouse_df['PERIOD END'] = pd.to_datetime(Townhouse_df['PERIOD END'])

In [35]:
#Creating period length in days variable for Tara's Datasets: Single Family and Townhouse
SingleFamily_df['Period Length (Days)'] = (SingleFamily_df['PERIOD END'] - SingleFamily_df['PERIOD BEGIN']).dt.days + 1
Townhouse_df['Period Length (Days)'] = (Townhouse_df['PERIOD END'] - Townhouse_df['PERIOD BEGIN']).dt.days + 1

Checking to see if any columns are missing again - verification after making the updates above:

In [42]:
singleFamUpdated_columns = set(SingleFamily_df.columns)

In [43]:
townhouseUpdated_columns = set(Townhouse_df.columns)

In [44]:
condoUpdated_columns = set(Condo_df.columns)

In [45]:
starterHomeUpdated_columns = set(StarterHome_df.columns)

In [46]:
#in Tara's Dataset, not in Justin dataset
print("Columns in Single Family, NOT in Condo: ")
print(singleFamUpdated_columns - condoUpdated_columns)

Columns in Single Family, NOT in Condo:
set()

In [47]:
#in Tara's Dataset, not in Justin dataset
print("Columns in Townhouse, NOT in Condo: ")
print(townhouseUpdated_columns - condoUpdated_columns)

Columns in Townhouse, NOT in Condo:
set()

In [48]:
#in Tara's Dataset, not in Justin dataset
print("Columns in Single Family, NOT in StarterHome: ")
print(singleFamUpdated_columns - starterHomeUpdated_columns)

Columns in Single Family, NOT in StarterHome:
set()

In [49]:
#in Tara's Dataset, not in Justin dataset
print("Columns in Single Family, NOT in StarterHome: ")
print(townhouseUpdated_columns - starterHomeUpdated_columns)

Columns in Single Family, NOT in StarterHome:
set()

In [50]:
#in Justin's Dataset, not in Tara dataset
print("Columns in Condo, NOT in Single Family: ")
print(condoUpdated_columns - singleFamUpdated_columns)

Columns in Condo, NOT in Single Family:
set()

In [51]:
#in Justin's Dataset, not in Tara dataset
print("Columns in Condo, NOT in Townhouse: ")
print(condoUpdated_columns - townhouseUpdated_columns)

Columns in Condo, NOT in Townhouse:
set()

In [52]:
#in Justin's Dataset, not in Tara dataset
print("Columns in StarterHome, NOT in Townhouse: ")
print(starterHomeUpdated_columns - townhouseUpdated_columns)

Columns in StarterHome, NOT in Townhouse:
set()

In [53]:
#in Justin's Dataset, not in Tara dataset
print("Columns in StarterHome, NOT in Single Family: ")
print(starterHomeUpdated_columns - singleFamUpdated_columns)

Columns in StarterHome, NOT in Single Family:
set()

Verifications before Concatanating

In [54]:
#Checking the ordering of columns between Single Fam and Condo datasets
print(SingleFamily_df.columns.tolist() == Condo_df.columns.tolist())

False

In [55]:
#Checking the ordering of columns between Single Fam and Townhouse datasets
print(SingleFamily_df.columns.tolist() == Townhouse_df.columns.tolist())

True

In [56]:
#Checking the ordering of columns between Single Fam and Starter Home datasets
print(SingleFamily_df.columns.tolist() == StarterHome_df.columns.tolist())

False

In [57]:
#Checking the ordering of columns between Condo and Townhouse datasets
print(Condo_df.columns.tolist() == Townhouse_df.columns.tolist())

False

In [58]:
#Checking the ordering of columns between Condo and StarterHome datasets
print(Condo_df.columns.tolist() == StarterHome_df.columns.tolist())

True

In [59]:
#Checking the ordering of columns between Townhouse and StarterHome datasets
print(Townhouse_df.columns.tolist() == StarterHome_df.columns.tolist())

False

In [60]:
#DELETE THIS CODE CHUNK
# Check if Datatypes across all dataframes are the same:
print(SingleFamily_df.dtypes.equals(Condo_df.dtypes))
print(SingleFamily_df.dtypes.equals(Townhouse_df.dtypes))
print(SingleFamily_df.dtypes.equals(StarterHome_df.dtypes))
print(Townhouse_df.dtypes.equals(Condo_df.dtypes))
print(Townhouse_df.dtypes.equals(StarterHome_df.dtypes))
print(StarterHome_df.dtypes.equals(Condo_df.dtypes))

False
True
False
False
False
False

In [61]:
singleFam_dtypes = SingleFamily_df.dtypes.sort_index()
condo_dtypes = Condo_df.dtypes.sort_index()
townhouse_dtypes = Townhouse_df.dtypes.sort_index()
starterHome_dtypes = StarterHome_df.dtypes.sort_index()

In [62]:
print(singleFam_dtypes.equals(condo_dtypes))

False

In [66]:
diff_SingleFamandCondo = singleFam_dtypes.compare(condo_dtypes)
print(diff_SingleFamandCondo)

                        self   other
PERIOD BEGIN  datetime64[ns]  object
PERIOD END    datetime64[ns]  object

In [64]:
print(singleFam_dtypes.equals(townhouse_dtypes))

True

In [65]:
print(singleFam_dtypes.equals(starterHome_dtypes))

False

In [68]:
diff_SingleFamandStarterHome = singleFam_dtypes.compare(starterHome_dtypes)
print(diff_SingleFamandStarterHome)

                                       self   other
MONTHLY HOUSING PAYMENT ($)         float64   int64
PERIOD BEGIN                 datetime64[ns]  object
PERIOD END                   datetime64[ns]  object

In [69]:
print(townhouse_dtypes.equals(condo_dtypes))

False

In [70]:
diff_TownhouseandCondo = townhouse_dtypes.compare(condo_dtypes)
print(diff_TownhouseandCondo)

                        self   other
PERIOD BEGIN  datetime64[ns]  object
PERIOD END    datetime64[ns]  object

In [71]:
print(townhouse_dtypes.equals(starterHome_dtypes))

False

In [72]:
diff_TownhouseandStarterHome = townhouse_dtypes.compare(starterHome_dtypes)
print(diff_TownhouseandStarterHome)

                                       self   other
MONTHLY HOUSING PAYMENT ($)         float64   int64
PERIOD BEGIN                 datetime64[ns]  object
PERIOD END                   datetime64[ns]  object

In [73]:
diff_CondoandStarterHome = condo_dtypes.compare(starterHome_dtypes)
print(diff_CondoandStarterHome)

                                self  other
MONTHLY HOUSING PAYMENT ($)  float64  int64

**Further Data Revision - Ensuring all Data Types are the Same**

* Justins Data Sets : Condo and Starter Home:

    * Convert 'Period Begin' and 'Period End' to pandas datetime objects
    * Make sure 'Monthly Housing Payment ($)' is float variable

In [74]:
#converting 'PERIOD BEGIN' and 'PERIOD END' to datetime objects in Condo Dataframe
Condo_df['PERIOD BEGIN'] = pd.to_datetime(Condo_df['PERIOD BEGIN'])
Condo_df['PERIOD END'] = pd.to_datetime(Condo_df['PERIOD END'])

In [75]:
#converting 'PERIOD BEGIN' and 'PERIOD END' to datetime objects in StarterHome Dataframe
StarterHome_df['PERIOD BEGIN'] = pd.to_datetime(StarterHome_df['PERIOD BEGIN'])
StarterHome_df['PERIOD END'] = pd.to_datetime(StarterHome_df['PERIOD END'])

In [76]:
#Make Sure 'MONTHLY HOUSING PAYMENT ($)' is a float variable in Condo and StarterHome datasets
Condo_df['MONTHLY HOUSING PAYMENT ($)'] = Condo_df['MONTHLY HOUSING PAYMENT ($)'].astype(float)
StarterHome_df['MONTHLY HOUSING PAYMENT ($)'] = StarterHome_df['MONTHLY HOUSING PAYMENT ($)'].astype(float)

**Reverifying that variable data types are the same across all datasets**

In [77]:
singleFam_dtypes = SingleFamily_df.dtypes.sort_index()
condo_dtypes = Condo_df.dtypes.sort_index()
townhouse_dtypes = Townhouse_df.dtypes.sort_index()
starterHome_dtypes = StarterHome_df.dtypes.sort_index()

In [78]:
print(singleFam_dtypes.equals(condo_dtypes))
print(singleFam_dtypes.equals(townhouse_dtypes))
print(singleFam_dtypes.equals(starterHome_dtypes))
print(townhouse_dtypes.equals(condo_dtypes))
print(townhouse_dtypes.equals(starterHome_dtypes))
print(condo_dtypes.equals(starterHome_dtypes))

True
True
True
True
True
True

**Concatenation**

In [79]:
combinedProperty_df = pd.concat([SingleFamily_df, Townhouse_df, Condo_df, StarterHome_df], ignore_index=True)
print(combinedProperty_df.shape)

(43260, 42)

In [80]:
SingleFamily_df.shape

(10920, 42)

In [81]:
Townhouse_df.shape

(10710, 42)

In [82]:
Condo_df.shape

(10920, 42)

In [83]:
StarterHome_df.shape

(10710, 42)

In [84]:
combinedProperty_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,SHARE OF INCOME ON HOUSING (%) Prop,SHARE OF INCOME ON HOUSING YOY (PPTS) Prop,AFFORDABLE LISTING SHARE (%) Prop,AFFORDABLE LISTING SHARE YOY (PPTS) Prop,YEARS TO SAVE DOWN PAYMENT YOY (%) Prop,MEDIAN SALE PRICE YOY (%) Prop,HOMES SOLD YOY (%) Prop,Season,Year-Month,Period Length (Days)
0,Monthly,2026-06-01,2026-06-30,Alabama,Single Family,Homeowner,3.5,90532.0,-1.49,31.52,...,0.3152,-0.0181,0.4057,0.0287,-0.0276,0.0130,0.0832,Summer,2026-06,30
1,Monthly,2026-05-01,2026-05-31,Alabama,Single Family,Homeowner,3.5,90652.0,-0.56,31.56,...,0.3156,-0.0150,0.4212,0.0419,-0.0142,0.0269,0.0091,Spring,2026-05,31
2,Monthly,2026-04-01,2026-04-30,Alabama,Single Family,Homeowner,3.5,88160.0,0.65,30.69,...,0.3069,-0.0107,0.4302,0.0365,-0.0003,0.0413,0.0217,Spring,2026-04,30
3,Monthly,2026-03-01,2026-03-31,Alabama,Single Family,Homeowner,3.5,86472.0,-1.26,30.11,...,0.3011,-0.0165,0.4482,0.0405,-0.0133,0.0279,0.0641,Spring,2026-03,31
4,Monthly,2026-02-01,2026-02-28,Alabama,Single Family,Homeowner,3.5,82901.0,-3.96,28.86,...,0.2886,-0.0244,0.4824,0.0765,-0.0137,0.0274,0.0637,Winter,2026-02,28

In [85]:
combinedProperty_df.tail()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,SHARE OF INCOME ON HOUSING (%) Prop,SHARE OF INCOME ON HOUSING YOY (PPTS) Prop,AFFORDABLE LISTING SHARE (%) Prop,AFFORDABLE LISTING SHARE YOY (PPTS) Prop,YEARS TO SAVE DOWN PAYMENT YOY (%) Prop,MEDIAN SALE PRICE YOY (%) Prop,HOMES SOLD YOY (%) Prop,Season,Year-Month,Period Length (Days)
43255,Monthly,2023-05-01,2023-05-31,Wyoming,Starter Home,Homeowner,20.0,52048.0,30.61,17.36,...,0.1736,0.0374,0.9330,-0.0565,0.1428,0.1707,-0.0452,Spring,2023-05,30
43256,Monthly,2023-04-01,2023-04-30,Wyoming,Starter Home,Homeowner,20.0,50965.0,31.95,17.00,...,0.1700,0.0380,0.9558,-0.0413,0.1366,0.1644,-0.0984,Spring,2023-04,29
43257,Monthly,2023-03-01,2023-03-31,Wyoming,Starter Home,Homeowner,20.0,51518.0,44.78,17.18,...,0.1718,0.0502,0.9558,-0.0365,0.1322,0.1599,-0.2097,Spring,2023-03,30
43258,Monthly,2023-02-01,2023-02-28,Wyoming,Starter Home,Homeowner,20.0,49399.0,44.26,16.48,...,0.1648,0.0478,0.9704,-0.0209,0.1108,0.1379,-0.2932,Winter,2023-02,27
43259,Monthly,2023-01-01,2023-01-31,Wyoming,Starter Home,Homeowner,20.0,48995.0,47.05,16.34,...,0.1634,0.0496,0.9719,-0.0194,0.0964,0.1232,-0.3612,Winter,2023-01,30

In [86]:
combinedProperty_df.dtypes

FREQUENCY                                             object
PERIOD BEGIN                                  datetime64[ns]
PERIOD END                                    datetime64[ns]
REGION NAME                                           object
PROPERTY TYPE                                         object
INCOME GROUP                                          object
DOWN PAYMENT PERCENT (%)                             float64
INCOME REQUIRED ($)                                  float64
INCOME REQUIRED YOY (%)                              float64
SHARE OF INCOME ON HOUSING (%)                       float64
SHARE OF INCOME ON HOUSING YOY (PPTS)                float64
AFFORDABLE LISTING SHARE (%)                         float64
AFFORDABLE LISTING SHARE YOY (PPTS)                  float64
YEARS TO SAVE DOWN PAYMENT                           float64
YEARS TO SAVE DOWN PAYMENT YOY (%)                   float64
MONTHLY HOUSING PAYMENT ($)                          float64
MONTHLY MORTGAGE PAYMENT ($)                         float64
MONTHLY PROPERTY TAX ($)                             float64
MONTHLY PROPERTY INSURANCE ($)                       float64
MONTHLY PMI ($)                                      float64
DOWN PAYMENT AMOUNT ($)                              float64
MEDIAN HOUSEHOLD INCOME ($)                          float64
MEDIAN SALE PRICE ($)                                float64
MEDIAN SALE PRICE YOY (%)                            float64
HOMES SOLD                                           float64
HOMES SOLD YOY (%)                                   float64
Year                                                   int64
Month                                                  int64
Month Name                                            object
Quarter                                                int64
DOWN PAYMENT AMOUNT ($) Prop                         float64
INCOME REQUIRED YOY (%) Prop                         float64
SHARE OF INCOME ON HOUSING (%) Prop                  float64
SHARE OF INCOME ON HOUSING YOY (PPTS) Prop           float64
AFFORDABLE LISTING SHARE (%) Prop                    float64
AFFORDABLE LISTING SHARE YOY (PPTS) Prop             float64
YEARS TO SAVE DOWN PAYMENT YOY (%) Prop              float64
MEDIAN SALE PRICE YOY (%) Prop                       float64
HOMES SOLD YOY (%) Prop                              float64
Season                                                object
Year-Month                                            object
Period Length (Days)                                   int64
dtype: object

In [87]:
combinedProperty_df.to_csv('combinedPropertyDataset.csv', index=False)