In [1]:
#import statements
import pandas as pd

In [2]:
originalSingleFamily_df = pd.read_csv("SingleFamily_Redfin.csv")

In [3]:
#inspecting the head of the original single family dataframe
originalSingleFamily_df.head()

,LAST UPDATED,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION TYPE,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),...,MONTHLY MORTGAGE PAYMENT ($),MONTHLY PROPERTY TAX ($),MONTHLY PROPERTY INSURANCE ($),MONTHLY PMI ($),DOWN PAYMENT AMOUNT ($),MEDIAN HOUSEHOLD INCOME ($),MEDIAN SALE PRICE ($),MEDIAN SALE PRICE YOY (%),HOMES SOLD,HOMES SOLD YOY (%)
0,2026-07-28,Monthly,2026-06-01,2026-06-30,State,Alabama,Single Family,Homeowner,3.5,90532.0,...,1851.0,71.0,127.0,215.0,10633.0,86165,303787.0,1.30,5782.0,8.32
1,2026-07-28,Monthly,2026-05-01,2026-05-31,State,Alabama,Single Family,Homeowner,3.5,90652.0,...,1852.0,71.0,127.0,216.0,10692.0,86165,305490.0,2.69,5739.0,0.91
2,2026-07-28,Monthly,2026-04-01,2026-04-30,State,Alabama,Single Family,Homeowner,3.5,88160.0,...,1797.0,70.0,125.0,212.0,10497.0,86165,299900.0,4.13,5225.0,2.17
3,2026-07-28,Monthly,2026-03-01,2026-03-31,State,Alabama,Single Family,Homeowner,3.5,86472.0,...,1757.0,69.0,124.0,211.0,10429.0,86165,297976.0,2.79,5014.0,6.41
4,2026-07-28,Monthly,2026-02-01,2026-02-28,State,Alabama,Single Family,Homeowner,3.5,82901.0,...,1680.0,67.0,120.0,205.0,10112.0,86165,288900.0,2.74,4007.0,6.37

In [4]:
#shape of original dataset: 10,921 rows x 28
originalSingleFamily_df.shape

(10920, 28)

In [5]:
#double checking that property type column is present in the dataset
if 'PROPERTY TYPE' in originalSingleFamily_df.columns:
    print("property type column is in single family dataset")
else:
    print("no property type column in single family dataset")

property type column is in single family dataset

In [6]:
#Check that NA values are recognized as missing values:
print("Number of Recognized Missing Values (NA) : ", originalSingleFamily_df.isna().sum())

Number of Recognized Missing Values (NA) :  LAST UPDATED                               0
FREQUENCY                                  0
PERIOD BEGIN                               0
PERIOD END                                 0
REGION TYPE                                0
REGION NAME                                0
PROPERTY TYPE                              0
INCOME GROUP                               0
DOWN PAYMENT PERCENT (%)                   0
INCOME REQUIRED ($)                      210
INCOME REQUIRED YOY (%)                  210
SHARE OF INCOME ON HOUSING (%)           210
SHARE OF INCOME ON HOUSING YOY (PPTS)    210
AFFORDABLE LISTING SHARE (%)             210
AFFORDABLE LISTING SHARE YOY (PPTS)      210
YEARS TO SAVE DOWN PAYMENT               210
YEARS TO SAVE DOWN PAYMENT YOY (%)       210
MONTHLY HOUSING PAYMENT ($)              210
MONTHLY MORTGAGE PAYMENT ($)             210
MONTHLY PROPERTY TAX ($)                 210
MONTHLY PROPERTY INSURANCE ($)           210
MONTHLY PMI ($)                          210
DOWN PAYMENT AMOUNT ($)                  210
MEDIAN HOUSEHOLD INCOME ($)                0
MEDIAN SALE PRICE ($)                    210
MEDIAN SALE PRICE YOY (%)                210
HOMES SOLD                               210
HOMES SOLD YOY (%)                       210
dtype: int64

In [13]:
#creating the cleaned single family dataframe copy - modify this dataset moving forward in next steps
cleanedSingleFamily_df = originalSingleFamily_df.copy()

In [14]:
#double-checking head of dataset
cleanedSingleFamily_df.head()

,LAST UPDATED,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION TYPE,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),...,MONTHLY MORTGAGE PAYMENT ($),MONTHLY PROPERTY TAX ($),MONTHLY PROPERTY INSURANCE ($),MONTHLY PMI ($),DOWN PAYMENT AMOUNT ($),MEDIAN HOUSEHOLD INCOME ($),MEDIAN SALE PRICE ($),MEDIAN SALE PRICE YOY (%),HOMES SOLD,HOMES SOLD YOY (%)
0,2026-07-28,Monthly,2026-06-01,2026-06-30,State,Alabama,Single Family,Homeowner,3.5,90532.0,...,1851.0,71.0,127.0,215.0,10633.0,86165,303787.0,1.30,5782.0,8.32
1,2026-07-28,Monthly,2026-05-01,2026-05-31,State,Alabama,Single Family,Homeowner,3.5,90652.0,...,1852.0,71.0,127.0,216.0,10692.0,86165,305490.0,2.69,5739.0,0.91
2,2026-07-28,Monthly,2026-04-01,2026-04-30,State,Alabama,Single Family,Homeowner,3.5,88160.0,...,1797.0,70.0,125.0,212.0,10497.0,86165,299900.0,4.13,5225.0,2.17
3,2026-07-28,Monthly,2026-03-01,2026-03-31,State,Alabama,Single Family,Homeowner,3.5,86472.0,...,1757.0,69.0,124.0,211.0,10429.0,86165,297976.0,2.79,5014.0,6.41
4,2026-07-28,Monthly,2026-02-01,2026-02-28,State,Alabama,Single Family,Homeowner,3.5,82901.0,...,1680.0,67.0,120.0,205.0,10112.0,86165,288900.0,2.74,4007.0,6.37

In [15]:
#dropping 'LAST UPDATED' and 'REGION TYPE' columns from cleaned dataset:
cleanedSingleFamily_df = cleanedSingleFamily_df.drop(columns = ['LAST UPDATED', 'REGION TYPE'])

In [16]:
cleanedSingleFamily_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,MONTHLY MORTGAGE PAYMENT ($),MONTHLY PROPERTY TAX ($),MONTHLY PROPERTY INSURANCE ($),MONTHLY PMI ($),DOWN PAYMENT AMOUNT ($),MEDIAN HOUSEHOLD INCOME ($),MEDIAN SALE PRICE ($),MEDIAN SALE PRICE YOY (%),HOMES SOLD,HOMES SOLD YOY (%)
0,Monthly,2026-06-01,2026-06-30,Alabama,Single Family,Homeowner,3.5,90532.0,-1.49,31.52,...,1851.0,71.0,127.0,215.0,10633.0,86165,303787.0,1.30,5782.0,8.32
1,Monthly,2026-05-01,2026-05-31,Alabama,Single Family,Homeowner,3.5,90652.0,-0.56,31.56,...,1852.0,71.0,127.0,216.0,10692.0,86165,305490.0,2.69,5739.0,0.91
2,Monthly,2026-04-01,2026-04-30,Alabama,Single Family,Homeowner,3.5,88160.0,0.65,30.69,...,1797.0,70.0,125.0,212.0,10497.0,86165,299900.0,4.13,5225.0,2.17
3,Monthly,2026-03-01,2026-03-31,Alabama,Single Family,Homeowner,3.5,86472.0,-1.26,30.11,...,1757.0,69.0,124.0,211.0,10429.0,86165,297976.0,2.79,5014.0,6.41
4,Monthly,2026-02-01,2026-02-28,Alabama,Single Family,Homeowner,3.5,82901.0,-3.96,28.86,...,1680.0,67.0,120.0,205.0,10112.0,86165,288900.0,2.74,4007.0,6.37

In [17]:
#VERIFICATION: double checking that 'LAST UPDATED' and 'REGION TYPE' columns were dropped from cleaned dataset successfully

dropped_cols = {'LAST UPDATED', 'REGION TYPE'}

if dropped_cols.issubset(cleanedSingleFamily_df.columns):
    print("dropped columns are present!")
else:
    print("dropped columns are not present!")

dropped columns are not present!

In [19]:
#Pandas Date Time Formatting:

#Converting Period Begin and Period End to pandas date time objects
cleanedSingleFamily_df['PERIOD BEGIN'] = pd.to_datetime(cleanedSingleFamily_df['PERIOD BEGIN'])
cleanedSingleFamily_df['PERIOD END'] = pd.to_datetime(cleanedSingleFamily_df['PERIOD END'])

In [20]:
#Verifying that period begin and period end were properly date time formatted:
print(cleanedSingleFamily_df['PERIOD BEGIN'].dtype)
print(cleanedSingleFamily_df['PERIOD END'].dtype)

datetime64[ns]
datetime64[ns]

In [22]:
#creating new columns from pandas datetime columns for seasonality
cleanedSingleFamily_df['Year'] = cleanedSingleFamily_df['PERIOD BEGIN'].dt.year
cleanedSingleFamily_df['Month'] = cleanedSingleFamily_df['PERIOD BEGIN'].dt.month
cleanedSingleFamily_df['Month_Name'] = cleanedSingleFamily_df['PERIOD BEGIN'].dt.month_name()
cleanedSingleFamily_df['Quarter'] = cleanedSingleFamily_df['PERIOD BEGIN'].dt.quarter

In [23]:
#VERIFICATION: double checking that added date year, month, month name, and quarter columns are present

addedDate_cols = {'Year', 'Month', 'Month_Name', 'Quarter'}

if addedDate_cols.issubset(cleanedSingleFamily_df.columns):
    print("added date columns are present!")
else:
    print("added date columns are not present!")

added date columns are present!

In [24]:
cleanedSingleFamily_df.columns

Index(['FREQUENCY', 'PERIOD BEGIN', 'PERIOD END', 'REGION NAME',
       'PROPERTY TYPE', 'INCOME GROUP', 'DOWN PAYMENT PERCENT (%)',
       'INCOME REQUIRED ($)', 'INCOME REQUIRED YOY (%)',
       'SHARE OF INCOME ON HOUSING (%)',
       'SHARE OF INCOME ON HOUSING YOY (PPTS)', 'AFFORDABLE LISTING SHARE (%)',
       'AFFORDABLE LISTING SHARE YOY (PPTS)', 'YEARS TO SAVE DOWN PAYMENT',
       'YEARS TO SAVE DOWN PAYMENT YOY (%)', 'MONTHLY HOUSING PAYMENT ($)',
       'MONTHLY MORTGAGE PAYMENT ($)', 'MONTHLY PROPERTY TAX ($)',
       'MONTHLY PROPERTY INSURANCE ($)', 'MONTHLY PMI ($)',
       'DOWN PAYMENT AMOUNT ($)', 'MEDIAN HOUSEHOLD INCOME ($)',
       'MEDIAN SALE PRICE ($)', 'MEDIAN SALE PRICE YOY (%)', 'HOMES SOLD',
       'HOMES SOLD YOY (%)', 'Year', 'Month', 'Month_Name', 'Quarter'],
      dtype='object')

In [25]:
percent_cols = [
    'DOWN PAYMENT AMOUNT ($)',
    'INCOME REQUIRED YOY (%)',
    'SHARE OF INCOME ON HOUSING (%)',
    'SHARE OF INCOME ON HOUSING YOY (PPTS)',
    'AFFORDABLE LISTING SHARE (%)',
    'AFFORDABLE LISTING SHARE YOY (PPTS)',
    'YEARS TO SAVE DOWN PAYMENT YOY (%)',
    'MEDIAN SALE PRICE YOY (%)',
    'HOMES SOLD YOY (%)'
]

In [28]:
#double checking that the data types of percent_cols are currently float values:
for col in percent_cols:
    print("col name: ", col, " data type: ", cleanedSingleFamily_df[col].dtype)

col name:  DOWN PAYMENT AMOUNT ($)  data type:  float64
col name:  INCOME REQUIRED YOY (%)  data type:  float64
col name:  SHARE OF INCOME ON HOUSING (%)  data type:  float64
col name:  SHARE OF INCOME ON HOUSING YOY (PPTS)  data type:  float64
col name:  AFFORDABLE LISTING SHARE (%)  data type:  float64
col name:  AFFORDABLE LISTING SHARE YOY (PPTS)  data type:  float64
col name:  YEARS TO SAVE DOWN PAYMENT YOY (%)  data type:  float64
col name:  MEDIAN SALE PRICE YOY (%)  data type:  float64
col name:  HOMES SOLD YOY (%)  data type:  float64

In [29]:
#proportionalizing the percent columns, giving them a new column (a copy of the original percentage col / 100)
for col in percent_cols:
    newColName = col + ' Prop'
    cleanedSingleFamily_df[newColName] = cleanedSingleFamily_df[col] / 100

In [30]:
#verifying that those proportion columns were made, and check their data types are float values

cleanedSingleFamily_df.columns

Index(['FREQUENCY', 'PERIOD BEGIN', 'PERIOD END', 'REGION NAME',
       'PROPERTY TYPE', 'INCOME GROUP', 'DOWN PAYMENT PERCENT (%)',
       'INCOME REQUIRED ($)', 'INCOME REQUIRED YOY (%)',
       'SHARE OF INCOME ON HOUSING (%)',
       'SHARE OF INCOME ON HOUSING YOY (PPTS)', 'AFFORDABLE LISTING SHARE (%)',
       'AFFORDABLE LISTING SHARE YOY (PPTS)', 'YEARS TO SAVE DOWN PAYMENT',
       'YEARS TO SAVE DOWN PAYMENT YOY (%)', 'MONTHLY HOUSING PAYMENT ($)',
       'MONTHLY MORTGAGE PAYMENT ($)', 'MONTHLY PROPERTY TAX ($)',
       'MONTHLY PROPERTY INSURANCE ($)', 'MONTHLY PMI ($)',
       'DOWN PAYMENT AMOUNT ($)', 'MEDIAN HOUSEHOLD INCOME ($)',
       'MEDIAN SALE PRICE ($)', 'MEDIAN SALE PRICE YOY (%)', 'HOMES SOLD',
       'HOMES SOLD YOY (%)', 'Year', 'Month', 'Month_Name', 'Quarter',
       'DOWN PAYMENT AMOUNT ($) Prop', 'INCOME REQUIRED YOY (%) Prop',
       'SHARE OF INCOME ON HOUSING (%) Prop',
       'SHARE OF INCOME ON HOUSING YOY (PPTS) Prop',
       'AFFORDABLE LISTING SHARE (%) Prop',
       'AFFORDABLE LISTING SHARE YOY (PPTS) Prop',
       'YEARS TO SAVE DOWN PAYMENT YOY (%) Prop',
       'MEDIAN SALE PRICE YOY (%) Prop', 'HOMES SOLD YOY (%) Prop'],
      dtype='object')

In [31]:
print(cleanedSingleFamily_df.dtypes)

FREQUENCY                                             object
PERIOD BEGIN                                  datetime64[ns]
PERIOD END                                    datetime64[ns]
REGION NAME                                           object
PROPERTY TYPE                                         object
INCOME GROUP                                          object
DOWN PAYMENT PERCENT (%)                             float64
INCOME REQUIRED ($)                                  float64
INCOME REQUIRED YOY (%)                              float64
SHARE OF INCOME ON HOUSING (%)                       float64
SHARE OF INCOME ON HOUSING YOY (PPTS)                float64
AFFORDABLE LISTING SHARE (%)                         float64
AFFORDABLE LISTING SHARE YOY (PPTS)                  float64
YEARS TO SAVE DOWN PAYMENT                           float64
YEARS TO SAVE DOWN PAYMENT YOY (%)                   float64
MONTHLY HOUSING PAYMENT ($)                          float64
MONTHLY MORTGAGE PAYMENT ($)                         float64
MONTHLY PROPERTY TAX ($)                             float64
MONTHLY PROPERTY INSURANCE ($)                       float64
MONTHLY PMI ($)                                      float64
DOWN PAYMENT AMOUNT ($)                              float64
MEDIAN HOUSEHOLD INCOME ($)                            int64
MEDIAN SALE PRICE ($)                                float64
MEDIAN SALE PRICE YOY (%)                            float64
HOMES SOLD                                           float64
HOMES SOLD YOY (%)                                   float64
Year                                                   int32
Month                                                  int32
Month_Name                                            object
Quarter                                                int32
DOWN PAYMENT AMOUNT ($) Prop                         float64
INCOME REQUIRED YOY (%) Prop                         float64
SHARE OF INCOME ON HOUSING (%) Prop                  float64
SHARE OF INCOME ON HOUSING YOY (PPTS) Prop           float64
AFFORDABLE LISTING SHARE (%) Prop                    float64
AFFORDABLE LISTING SHARE YOY (PPTS) Prop             float64
YEARS TO SAVE DOWN PAYMENT YOY (%) Prop              float64
MEDIAN SALE PRICE YOY (%) Prop                       float64
HOMES SOLD YOY (%) Prop                              float64
dtype: object

In [32]:
#converting median household income to float
cleanedSingleFamily_df['MEDIAN HOUSEHOLD INCOME ($)'] = cleanedSingleFamily_df['MEDIAN HOUSEHOLD INCOME ($)'].astype(float)

In [33]:
cleanedSingleFamily_df['MEDIAN HOUSEHOLD INCOME ($)'].dtype

dtype('float64')

In [34]:
#seasonal column mapping:

season_map = {
    12: 'Winter', 1: 'Winter', 2: 'Winter',
    3: 'Spring', 4: 'Spring', 5: 'Spring',
    6: 'Summer', 7: 'Summer', 8: 'Summer',
    9: 'Fall', 10: 'Fall', 11: 'Fall'
}

#Creating a season column
cleanedSingleFamily_df['Season'] = cleanedSingleFamily_df['Month'].map(season_map)

In [35]:
season_col = {'Season'}

if season_col.issubset(cleanedSingleFamily_df.columns):
    print("added season column is present!")
else:
    print("added season column is not present!")

added season column is present!

In [36]:
#finally seeing the cleanedSingleFamily_df
cleanedSingleFamily_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,DOWN PAYMENT AMOUNT ($) Prop,INCOME REQUIRED YOY (%) Prop,SHARE OF INCOME ON HOUSING (%) Prop,SHARE OF INCOME ON HOUSING YOY (PPTS) Prop,AFFORDABLE LISTING SHARE (%) Prop,AFFORDABLE LISTING SHARE YOY (PPTS) Prop,YEARS TO SAVE DOWN PAYMENT YOY (%) Prop,MEDIAN SALE PRICE YOY (%) Prop,HOMES SOLD YOY (%) Prop,Season
0,Monthly,2026-06-01,2026-06-30,Alabama,Single Family,Homeowner,3.5,90532.0,-1.49,31.52,...,106.33,-0.0149,0.3152,-0.0181,0.4057,0.0287,-0.0276,0.0130,0.0832,Summer
1,Monthly,2026-05-01,2026-05-31,Alabama,Single Family,Homeowner,3.5,90652.0,-0.56,31.56,...,106.92,-0.0056,0.3156,-0.0150,0.4212,0.0419,-0.0142,0.0269,0.0091,Spring
2,Monthly,2026-04-01,2026-04-30,Alabama,Single Family,Homeowner,3.5,88160.0,0.65,30.69,...,104.97,0.0065,0.3069,-0.0107,0.4302,0.0365,-0.0003,0.0413,0.0217,Spring
3,Monthly,2026-03-01,2026-03-31,Alabama,Single Family,Homeowner,3.5,86472.0,-1.26,30.11,...,104.29,-0.0126,0.3011,-0.0165,0.4482,0.0405,-0.0133,0.0279,0.0641,Spring
4,Monthly,2026-02-01,2026-02-28,Alabama,Single Family,Homeowner,3.5,82901.0,-3.96,28.86,...,101.12,-0.0396,0.2886,-0.0244,0.4824,0.0765,-0.0137,0.0274,0.0637,Winter

In [38]:
#downloading the cleaned notebook
cleanedSingleFamily_df.to_csv('SingleFamily_cleanedDF.csv', index=False)