In [1]:
#import statements
import pandas as pd

In [2]:
#reading in the original townhouse dataset
originalTownhouse_df = pd.read_csv("TownHouse_Redfin.csv")

In [3]:
originalTownhouse_df.head()

,LAST UPDATED,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION TYPE,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),...,MONTHLY MORTGAGE PAYMENT ($),MONTHLY PROPERTY TAX ($),MONTHLY PROPERTY INSURANCE ($),MONTHLY PMI ($),DOWN PAYMENT AMOUNT ($),MEDIAN HOUSEHOLD INCOME ($),MEDIAN SALE PRICE ($),MEDIAN SALE PRICE YOY (%),HOMES SOLD,HOMES SOLD YOY (%)
0,2026-07-28,Monthly,2026-06-01,2026-06-30,State,Alabama,Townhouse,Homeowner,3.5,83234.0,...,1702.0,65.0,116.0,198.0,9775.0,86165,279300.0,8.16,201.0,17.15
1,2026-07-28,Monthly,2026-05-01,2026-05-31,State,Alabama,Townhouse,Homeowner,3.5,77895.0,...,1591.0,61.0,109.0,186.0,9188.0,86165,262500.0,1.00,174.0,-14.29
2,2026-07-28,Monthly,2026-04-01,2026-04-30,State,Alabama,Townhouse,Homeowner,3.5,73462.0,...,1497.0,58.0,104.0,177.0,8747.0,86165,249900.0,-8.79,143.0,-13.86
3,2026-07-28,Monthly,2026-03-01,2026-03-31,State,Alabama,Townhouse,Homeowner,3.5,74524.0,...,1515.0,60.0,107.0,182.0,8988.0,86165,256803.0,9.28,157.0,-1.26
4,2026-07-28,Monthly,2026-02-01,2026-02-28,State,Alabama,Townhouse,Homeowner,3.5,73030.0,...,1480.0,59.0,106.0,180.0,8908.0,86165,254500.0,-1.55,112.0,-15.15

In [4]:
#townhouse dataset shape: 10,710 rows x 28 columns
originalTownhouse_df.shape

(10710, 28)

In [5]:
#double checking that property type column is present in the townhouse dataset
if 'PROPERTY TYPE' in originalTownhouse_df.columns:
    print("property type column is in townhouse dataset")
else:
    print("no property type column in townhouse dataset")

property type column is in townhouse dataset

In [6]:
#checking if na values are getting recognized

#Check that NA values are recognized as missing values:
print("Number of Recognized Missing Values (NA) : ", originalTownhouse_df.isna().sum())

Number of Recognized Missing Values (NA) :  LAST UPDATED                               0
FREQUENCY                                  0
PERIOD BEGIN                               0
PERIOD END                                 0
REGION TYPE                                0
REGION NAME                                0
PROPERTY TYPE                              0
INCOME GROUP                               0
DOWN PAYMENT PERCENT (%)                   0
INCOME REQUIRED ($)                      525
INCOME REQUIRED YOY (%)                  655
SHARE OF INCOME ON HOUSING (%)           525
SHARE OF INCOME ON HOUSING YOY (PPTS)    655
AFFORDABLE LISTING SHARE (%)             205
AFFORDABLE LISTING SHARE YOY (PPTS)      315
YEARS TO SAVE DOWN PAYMENT               525
YEARS TO SAVE DOWN PAYMENT YOY (%)       655
MONTHLY HOUSING PAYMENT ($)              525
MONTHLY MORTGAGE PAYMENT ($)             525
MONTHLY PROPERTY TAX ($)                 525
MONTHLY PROPERTY INSURANCE ($)           525
MONTHLY PMI ($)                          525
DOWN PAYMENT AMOUNT ($)                  525
MEDIAN HOUSEHOLD INCOME ($)                0
MEDIAN SALE PRICE ($)                    525
MEDIAN SALE PRICE YOY (%)                655
HOMES SOLD                               525
HOMES SOLD YOY (%)                       655
dtype: int64

In [7]:
#creating the cleaned townhouse dataframe copy - modify this dataset moving forward in next steps
cleanedTownhouse_df = originalTownhouse_df.copy()

In [8]:
cleanedTownhouse_df.head()

,LAST UPDATED,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION TYPE,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),...,MONTHLY MORTGAGE PAYMENT ($),MONTHLY PROPERTY TAX ($),MONTHLY PROPERTY INSURANCE ($),MONTHLY PMI ($),DOWN PAYMENT AMOUNT ($),MEDIAN HOUSEHOLD INCOME ($),MEDIAN SALE PRICE ($),MEDIAN SALE PRICE YOY (%),HOMES SOLD,HOMES SOLD YOY (%)
0,2026-07-28,Monthly,2026-06-01,2026-06-30,State,Alabama,Townhouse,Homeowner,3.5,83234.0,...,1702.0,65.0,116.0,198.0,9775.0,86165,279300.0,8.16,201.0,17.15
1,2026-07-28,Monthly,2026-05-01,2026-05-31,State,Alabama,Townhouse,Homeowner,3.5,77895.0,...,1591.0,61.0,109.0,186.0,9188.0,86165,262500.0,1.00,174.0,-14.29
2,2026-07-28,Monthly,2026-04-01,2026-04-30,State,Alabama,Townhouse,Homeowner,3.5,73462.0,...,1497.0,58.0,104.0,177.0,8747.0,86165,249900.0,-8.79,143.0,-13.86
3,2026-07-28,Monthly,2026-03-01,2026-03-31,State,Alabama,Townhouse,Homeowner,3.5,74524.0,...,1515.0,60.0,107.0,182.0,8988.0,86165,256803.0,9.28,157.0,-1.26
4,2026-07-28,Monthly,2026-02-01,2026-02-28,State,Alabama,Townhouse,Homeowner,3.5,73030.0,...,1480.0,59.0,106.0,180.0,8908.0,86165,254500.0,-1.55,112.0,-15.15

In [9]:
#dropping 'LAST UPDATED' and 'REGION TYPE' columns from cleaned townhouse dataset:
cleanedTownhouse_df = cleanedTownhouse_df.drop(columns = ['LAST UPDATED', 'REGION TYPE'])

In [10]:
cleanedTownhouse_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,MONTHLY MORTGAGE PAYMENT ($),MONTHLY PROPERTY TAX ($),MONTHLY PROPERTY INSURANCE ($),MONTHLY PMI ($),DOWN PAYMENT AMOUNT ($),MEDIAN HOUSEHOLD INCOME ($),MEDIAN SALE PRICE ($),MEDIAN SALE PRICE YOY (%),HOMES SOLD,HOMES SOLD YOY (%)
0,Monthly,2026-06-01,2026-06-30,Alabama,Townhouse,Homeowner,3.5,83234.0,5.18,28.98,...,1702.0,65.0,116.0,198.0,9775.0,86165,279300.0,8.16,201.0,17.15
1,Monthly,2026-05-01,2026-05-31,Alabama,Townhouse,Homeowner,3.5,77895.0,-2.20,27.12,...,1591.0,61.0,109.0,186.0,9188.0,86165,262500.0,1.00,174.0,-14.29
2,Monthly,2026-04-01,2026-04-30,Alabama,Townhouse,Homeowner,3.5,73462.0,-11.84,25.58,...,1497.0,58.0,104.0,177.0,8747.0,86165,249900.0,-8.79,143.0,-13.86
3,Monthly,2026-03-01,2026-03-31,Alabama,Townhouse,Homeowner,3.5,74524.0,4.98,25.95,...,1515.0,60.0,107.0,182.0,8988.0,86165,256803.0,9.28,157.0,-1.26
4,Monthly,2026-02-01,2026-02-28,Alabama,Townhouse,Homeowner,3.5,73030.0,-7.96,25.43,...,1480.0,59.0,106.0,180.0,8908.0,86165,254500.0,-1.55,112.0,-15.15

In [11]:
#VERIFICATION: double checking that 'LAST UPDATED' and 'REGION TYPE' columns were dropped from cleaned dataset successfully

dropped_cols = {'LAST UPDATED', 'REGION TYPE'}

if dropped_cols.issubset(cleanedTownhouse_df.columns):
    print("dropped columns are present!")
else:
    print("dropped columns are not present!")

dropped columns are not present!

In [12]:
#converting period begin and period end to pandas datetime objects
cleanedTownhouse_df['PERIOD BEGIN'] = pd.to_datetime(cleanedTownhouse_df['PERIOD BEGIN'])
cleanedTownhouse_df['PERIOD END'] = pd.to_datetime(cleanedTownhouse_df['PERIOD END'])

In [15]:
#Verifying that period begin and period end were properly date time formatted:
print(cleanedTownhouse_df['PERIOD BEGIN'].dtype)
print(cleanedTownhouse_df['PERIOD END'].dtype)

datetime64[ns]
datetime64[ns]

In [13]:
cleanedTownhouse_df['Year'] = cleanedTownhouse_df['PERIOD BEGIN'].dt.year
cleanedTownhouse_df['Month'] = cleanedTownhouse_df['PERIOD BEGIN'].dt.month
cleanedTownhouse_df['Month_Name'] = cleanedTownhouse_df['PERIOD BEGIN'].dt.month_name()
cleanedTownhouse_df['Quarter'] = cleanedTownhouse_df['PERIOD BEGIN'].dt.quarter

In [14]:
#VERIFICATION: double checking that added date year, month, month name, and quarter columns are present in townhouse dataset

addedDate_cols = {'Year', 'Month', 'Month_Name', 'Quarter'}

if addedDate_cols.issubset(cleanedTownhouse_df.columns):
    print("added date columns are present!")
else:
    print("added date columns are not present!")

added date columns are present!

In [16]:
percent_cols = [
    'DOWN PAYMENT AMOUNT ($)',
    'INCOME REQUIRED YOY (%)',
    'SHARE OF INCOME ON HOUSING (%)',
    'SHARE OF INCOME ON HOUSING YOY (PPTS)',
    'AFFORDABLE LISTING SHARE (%)',
    'AFFORDABLE LISTING SHARE YOY (PPTS)',
    'YEARS TO SAVE DOWN PAYMENT YOY (%)',
    'MEDIAN SALE PRICE YOY (%)',
    'HOMES SOLD YOY (%)'
]

In [17]:
#double checking that the data types of percent_cols are currently float values:
for col in percent_cols:
    print("col name: ", col, " data type: ", cleanedTownhouse_df[col].dtype)

col name:  DOWN PAYMENT AMOUNT ($)  data type:  float64
col name:  INCOME REQUIRED YOY (%)  data type:  float64
col name:  SHARE OF INCOME ON HOUSING (%)  data type:  float64
col name:  SHARE OF INCOME ON HOUSING YOY (PPTS)  data type:  float64
col name:  AFFORDABLE LISTING SHARE (%)  data type:  float64
col name:  AFFORDABLE LISTING SHARE YOY (PPTS)  data type:  float64
col name:  YEARS TO SAVE DOWN PAYMENT YOY (%)  data type:  float64
col name:  MEDIAN SALE PRICE YOY (%)  data type:  float64
col name:  HOMES SOLD YOY (%)  data type:  float64

In [18]:
#proportionalizing the percent columns, giving them a new column (a copy of the original percentage col / 100)
for col in percent_cols:
    newColName = col + ' Prop'
    cleanedTownhouse_df[newColName] = cleanedTownhouse_df[col] / 100

In [19]:
#verifying that those proportion columns were made, and check their data types are float values

cleanedTownhouse_df.columns

Index(['FREQUENCY', 'PERIOD BEGIN', 'PERIOD END', 'REGION NAME',
       'PROPERTY TYPE', 'INCOME GROUP', 'DOWN PAYMENT PERCENT (%)',
       'INCOME REQUIRED ($)', 'INCOME REQUIRED YOY (%)',
       'SHARE OF INCOME ON HOUSING (%)',
       'SHARE OF INCOME ON HOUSING YOY (PPTS)', 'AFFORDABLE LISTING SHARE (%)',
       'AFFORDABLE LISTING SHARE YOY (PPTS)', 'YEARS TO SAVE DOWN PAYMENT',
       'YEARS TO SAVE DOWN PAYMENT YOY (%)', 'MONTHLY HOUSING PAYMENT ($)',
       'MONTHLY MORTGAGE PAYMENT ($)', 'MONTHLY PROPERTY TAX ($)',
       'MONTHLY PROPERTY INSURANCE ($)', 'MONTHLY PMI ($)',
       'DOWN PAYMENT AMOUNT ($)', 'MEDIAN HOUSEHOLD INCOME ($)',
       'MEDIAN SALE PRICE ($)', 'MEDIAN SALE PRICE YOY (%)', 'HOMES SOLD',
       'HOMES SOLD YOY (%)', 'Year', 'Month', 'Month_Name', 'Quarter',
       'DOWN PAYMENT AMOUNT ($) Prop', 'INCOME REQUIRED YOY (%) Prop',
       'SHARE OF INCOME ON HOUSING (%) Prop',
       'SHARE OF INCOME ON HOUSING YOY (PPTS) Prop',
       'AFFORDABLE LISTING SHARE (%) Prop',
       'AFFORDABLE LISTING SHARE YOY (PPTS) Prop',
       'YEARS TO SAVE DOWN PAYMENT YOY (%) Prop',
       'MEDIAN SALE PRICE YOY (%) Prop', 'HOMES SOLD YOY (%) Prop'],
      dtype='object')

In [20]:
print(cleanedTownhouse_df.dtypes)

FREQUENCY                                             object
PERIOD BEGIN                                  datetime64[ns]
PERIOD END                                    datetime64[ns]
REGION NAME                                           object
PROPERTY TYPE                                         object
INCOME GROUP                                          object
DOWN PAYMENT PERCENT (%)                             float64
INCOME REQUIRED ($)                                  float64
INCOME REQUIRED YOY (%)                              float64
SHARE OF INCOME ON HOUSING (%)                       float64
SHARE OF INCOME ON HOUSING YOY (PPTS)                float64
AFFORDABLE LISTING SHARE (%)                         float64
AFFORDABLE LISTING SHARE YOY (PPTS)                  float64
YEARS TO SAVE DOWN PAYMENT                           float64
YEARS TO SAVE DOWN PAYMENT YOY (%)                   float64
MONTHLY HOUSING PAYMENT ($)                          float64
MONTHLY MORTGAGE PAYMENT ($)                         float64
MONTHLY PROPERTY TAX ($)                             float64
MONTHLY PROPERTY INSURANCE ($)                       float64
MONTHLY PMI ($)                                      float64
DOWN PAYMENT AMOUNT ($)                              float64
MEDIAN HOUSEHOLD INCOME ($)                            int64
MEDIAN SALE PRICE ($)                                float64
MEDIAN SALE PRICE YOY (%)                            float64
HOMES SOLD                                           float64
HOMES SOLD YOY (%)                                   float64
Year                                                   int32
Month                                                  int32
Month_Name                                            object
Quarter                                                int32
DOWN PAYMENT AMOUNT ($) Prop                         float64
INCOME REQUIRED YOY (%) Prop                         float64
SHARE OF INCOME ON HOUSING (%) Prop                  float64
SHARE OF INCOME ON HOUSING YOY (PPTS) Prop           float64
AFFORDABLE LISTING SHARE (%) Prop                    float64
AFFORDABLE LISTING SHARE YOY (PPTS) Prop             float64
YEARS TO SAVE DOWN PAYMENT YOY (%) Prop              float64
MEDIAN SALE PRICE YOY (%) Prop                       float64
HOMES SOLD YOY (%) Prop                              float64
dtype: object

In [21]:
#converting median household income to float
cleanedTownhouse_df['MEDIAN HOUSEHOLD INCOME ($)'] = cleanedTownhouse_df['MEDIAN HOUSEHOLD INCOME ($)'].astype(float)

In [22]:
cleanedTownhouse_df['MEDIAN HOUSEHOLD INCOME ($)'].dtype

dtype('float64')

In [23]:
#seasonal column mapping:

season_map = {
    12: 'Winter', 1: 'Winter', 2: 'Winter',
    3: 'Spring', 4: 'Spring', 5: 'Spring',
    6: 'Summer', 7: 'Summer', 8: 'Summer',
    9: 'Fall', 10: 'Fall', 11: 'Fall'
}

#Creating a season column
cleanedTownhouse_df['Season'] = cleanedTownhouse_df['Month'].map(season_map)

In [24]:
season_col = {'Season'}

if season_col.issubset(cleanedTownhouse_df.columns):
    print("added season column is present!")
else:
    print("added season column is not present!")

added season column is present!

In [25]:
#finally seeing the cleanedSingleFamily_df
cleanedTownhouse_df.head()

,FREQUENCY,PERIOD BEGIN,PERIOD END,REGION NAME,PROPERTY TYPE,INCOME GROUP,DOWN PAYMENT PERCENT (%),INCOME REQUIRED ($),INCOME REQUIRED YOY (%),SHARE OF INCOME ON HOUSING (%),...,DOWN PAYMENT AMOUNT ($) Prop,INCOME REQUIRED YOY (%) Prop,SHARE OF INCOME ON HOUSING (%) Prop,SHARE OF INCOME ON HOUSING YOY (PPTS) Prop,AFFORDABLE LISTING SHARE (%) Prop,AFFORDABLE LISTING SHARE YOY (PPTS) Prop,YEARS TO SAVE DOWN PAYMENT YOY (%) Prop,MEDIAN SALE PRICE YOY (%) Prop,HOMES SOLD YOY (%) Prop,Season
0,Monthly,2026-06-01,2026-06-30,Alabama,Townhouse,Homeowner,3.5,83234.0,5.18,28.98,...,97.75,0.0518,0.2898,0.0028,0.5095,-0.0076,0.0383,0.0816,0.1715,Summer
1,Monthly,2026-05-01,2026-05-31,Alabama,Townhouse,Homeowner,3.5,77895.0,-2.20,27.12,...,91.88,-0.0220,0.2712,-0.0176,0.5041,-0.0220,-0.0304,0.0100,-0.1429,Spring
2,Monthly,2026-04-01,2026-04-30,Alabama,Townhouse,Homeowner,3.5,73462.0,-11.84,25.58,...,87.47,-0.1184,0.2558,-0.0464,0.5293,0.0157,-0.1244,-0.0879,-0.1386,Spring
3,Monthly,2026-03-01,2026-03-31,Alabama,Townhouse,Homeowner,3.5,74524.0,4.98,25.95,...,89.88,0.0498,0.2595,0.0020,0.5407,0.0220,0.0491,0.0928,-0.0126,Spring
4,Monthly,2026-02-01,2026-02-28,Alabama,Townhouse,Homeowner,3.5,73030.0,-7.96,25.43,...,89.08,-0.0796,0.2543,-0.0335,0.5936,0.1027,-0.0549,-0.0155,-0.1515,Winter

In [26]:
#downloading the cleaned dataset from notebook
cleanedTownhouse_df.to_csv('Townhouse_cleanedDF.csv', index=False)